dependencies:
- name: kafka
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  version: 0.11.1
- name: compressor-ms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: dataconnector-ms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: frontapi-ms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: grouper-ms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: metadatapersistor-ms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
